services:
  - type: web
    name: treasure-and-friends
    env: python
    region: oregon
    branch: main
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py migrate --noinput &&
      gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    plan: free